lints.workspace = true

[package]
name = "netcalyx-pcap-reader"
version = "0.12.1"
edition = "2024"
authors = ["NetCalyx Authors"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/network-analytics/NetCalyx"
homepage = "https://github.com/network-analytics/NetCalyx"
description = """
Simple PCAP reader
"""
keywords = ["pcap", "protocol"]
categories = ["network-programming", "parsing"]

[dependencies]
pcap-parser = { workspace = true, features = ["data"] }
pdu = { workspace = true }
